### ISSUE TITLE
can't install pp distribution on docker container 

### ISSUE THREAD

**Issue by knbknb** [buepro/typo3-pizpalue#4]
**I can't install the pizpalu distribution through the TER, on  a typo3 instance based on a docker image. To be exact, on a v10.4 release (Docker v19.0.3). Installation is incomplete.**

This happens although I have installed a brandnew docker container  based on image "martinhelmich/typo3:10" which is close to an official image, and comes  preconfigured in a near-perfect state - at least that's what the Wizards from  Admin Tools ("Maintenance" Module etc) say.

The progressbar of the installer that runs within the "Get preconfigured distributions" starts, but stops rather quickly. All (?) extensions get fetched from the TER, but the site does not show up in the page tree. 

Some background information:

THe installation is fresh, it is not an upgrade, and I have root privileges  everywhere. 

Coming from typo3 v4, I have not worked with the PizPalu distribution before.
 
Is there a recommended Docker image that I should use? Typo3 v9 or another typo3 v10 (not 10.4?=  ? or should I try typo3 v11 ?

#### Enhancement request:
**And I think this scenario (Docker) should be mentioned in the "installation" section of your documentation.**

Maybe add a "Installation with Docker" paragraph to your documenation (which is already very good. Also the demo sites look awesome).

I'm using these settings in my docker-compose yml file (db server settings omitted)

```
  typo3_10_palu:
    image: martinhelmich/typo3:10
    volumes:
      - typo3_10_palu_volume:/var/www/html
    ports:
      - '8035:80'
    env_file:
      - .env_10
      - .env_10_palu
    environment:
      PHP_ENABLE_XDEBUG: 1
      MYSQL_DATABASE: typo3_10_palu
    links:
      - db
    restart: unless-stopped
```
